### ISSUE TITLE
Support for Launch Templates

### ISSUE THREAD

**Issue by tom-butler** [deitch/aws-asg-roller#17]
This looks like a great tool!

Only issue is I'm using Launch Templates for my ASGs, instead of Launch Configuration. Is this something can be added to this tool?

**Comment by deitch** [comment]
I would like to see that. Launch Templates slowly (or not so slowly?) are replacing Launch Configs, so it makes sense. Let's see what we can do.

**Comment by deitch** [comment]
Fortunately, this turns out to be pretty simple. The entire `LaunchConfiguration` logic is encapsulated [here](https://github.com/deitch/aws-asg-roller/blob/master/roller.go#L180-L193), where it groups it by "old instances" (those that should be terminated and replaced) and "new instances" (those that have the new config). The rest of this doesn't really care why it is grouped just leverages it.

The slightly difficult part will be behaviour when both config and template are set, but we can handle that.
